"""
Base Protocol Monitor
=====================

Abstract base class for protocol-specific monitoring.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Callable, Awaitable
import structlog

logger = structlog.get_logger(__name__)


class ProtocolType(Enum):
    """Types of DeFi protocols."""
    LENDING = "lending"
    DEX = "dex"
    STAKING = "staking"
    BRIDGE = "bridge"
    DERIVATIVES = "derivatives"
    YIELD = "yield"
    CDP = "cdp"


class AlertType(Enum):
    """Types of protocol alerts."""
    LIQUIDATION = "liquidation"
    LARGE_TRANSACTION = "large_transaction"
    TVL_DROP = "tvl_drop"
    PRICE_IMPACT = "price_impact"
    HEALTH_FACTOR_LOW = "health_factor_low"
    GOVERNANCE_ACTION = "governance_action"
    ORACLE_DEVIATION = "oracle_deviation"
    RATE_SPIKE = "rate_spike"
    POOL_IMBALANCE = "pool_imbalance"
    WITHDRAWAL_SURGE = "withdrawal_surge"


@dataclass
class ProtocolConfig:
    """Configuration for a protocol monitor."""
    protocol_id: str
    protocol_name: str
    protocol_type: ProtocolType
    chains: List[str]
    
    # Contract addresses per chain
    contracts: Dict[str, Dict[str, str]] = field(default_factory=dict)
    
    # Thresholds
    large_tx_threshold_usd: float = 100000
    tvl_drop_threshold_percent: float = 10
    health_factor_warning: float = 1.5
    health_factor_critical: float = 1.1
    price_impact_warning: float = 1.0  # 1%
    price_impact_critical: float = 5.0  # 5%
    
    # Event signatures to monitor
    event_signatures: Dict[str, str] = field(default_factory=dict)


@dataclass
class ProtocolAlert:
    """Alert generated by protocol monitor."""
    alert_id: str
    protocol_id: str
    protocol_name: str
    chain_id: str
    alert_type: AlertType
    severity: str  # critical, high, medium, low
    timestamp: datetime
    
    # Transaction details
    tx_hash: Optional[str] = None
    block_number: Optional[int] = None
    
    # Alert-specific data
    title: str = ""
    description: str = ""
    value_usd: float = 0.0
    
    # Additional context
    affected_address: Optional[str] = None
    affected_pool: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "alert_id": self.alert_id,
            "protocol_id": self.protocol_id,
            "protocol_name": self.protocol_name,
            "chain_id": self.chain_id,
            "alert_type": self.alert_type.value,
            "severity": self.severity,
            "timestamp": self.timestamp.isoformat(),
            "tx_hash": self.tx_hash,
            "block_number": self.block_number,
            "title": self.title,
            "description": self.description,
            "value_usd": self.value_usd,
            "affected_address": self.affected_address,
            "affected_pool": self.affected_pool,
            "metadata": self.metadata,
        }


@dataclass
class ProtocolMetrics:
    """Real-time metrics for a protocol."""
    protocol_id: str
    chain_id: str
    timestamp: datetime
    
    # TVL
    tvl_usd: float = 0.0
    tvl_change_24h_percent: float = 0.0
    
    # Volume
    volume_24h_usd: float = 0.0
    
    # Protocol-specific
    total_borrowed_usd: float = 0.0
    total_supplied_usd: float = 0.0
    utilization_rate: float = 0.0
    
    # Fees
    fees_24h_usd: float = 0.0
    
    # Risk metrics
    liquidations_24h_count: int = 0
    liquidations_24h_usd: float = 0.0
    
    # Additional metrics
    extra: Dict[str, Any] = field(default_factory=dict)


class ProtocolMonitor(ABC):
    """
    Abstract base class for protocol-specific monitoring.
    
    Implementations should:
    1. Parse protocol-specific events
    2. Track TVL and key metrics
    3. Detect liquidations and large transactions
    4. Generate alerts based on thresholds
    """
    
    def __init__(self, config: ProtocolConfig):
        self.config = config
        self.metrics: Dict[str, ProtocolMetrics] = {}  # chain_id -> metrics
        self.alert_handlers: List[Callable[[ProtocolAlert], Awaitable[Any]]] = []
        self._stats = {
            "events_processed": 0,
            "alerts_generated": 0,
            "liquidations_detected": 0,
            "large_txs_detected": 0,
        }
        
        logger.info(
            "protocol_monitor_initialized",
            protocol=config.protocol_id,
            chains=config.chains
        )
    
    def add_alert_handler(self, handler: Callable[[ProtocolAlert], Awaitable[Any]]):
        """Add handler for protocol alerts."""
        self.alert_handlers.append(handler)
    
    async def _notify_handlers(self, alert: ProtocolAlert):
        """Notify all alert handlers."""
        for handler in self.alert_handlers:
            try:
                await handler(alert)
            except Exception as e:
                logger.error("alert_handler_error", error=str(e), alert_id=alert.alert_id)
    
    @abstractmethod
    async def process_event(
        self,
        event_data: Dict[str, Any],
        chain_id: str,
        block_timestamp: datetime
    ) -> Optional[ProtocolAlert]:
        """
        Process a blockchain event.
        
        Returns an alert if one should be generated.
        """
        pass
    
    @abstractmethod
    async def get_metrics(self, chain_id: str) -> ProtocolMetrics:
        """Get current metrics for a chain."""
        pass
    
    @abstractmethod
    def get_event_signatures(self) -> Dict[str, str]:
        """Get event signatures this monitor handles."""
        pass
    
    def is_relevant_event(self, topic0: str) -> bool:
        """Check if event is relevant to this protocol."""
        return topic0.lower() in [s.lower() for s in self.get_event_signatures().keys()]
    
    def get_stats(self) -> Dict[str, Any]:
        """Get monitor statistics."""
        return {
            **self._stats,
            "protocol_id": self.config.protocol_id,
            "chains": self.config.chains,
        }
    
    async def create_alert(
        self,
        chain_id: str,
        alert_type: AlertType,
        severity: str,
        title: str,
        description: str,
        tx_hash: Optional[str] = None,
        block_number: Optional[int] = None,
        value_usd: float = 0.0,
        affected_address: Optional[str] = None,
        affected_pool: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> ProtocolAlert:
        """Create and emit a protocol alert."""
        self._stats["alerts_generated"] += 1
        
        alert = ProtocolAlert(
            alert_id=f"{self.config.protocol_id}_{chain_id}_{int(datetime.now(timezone.utc).timestamp())}",
            protocol_id=self.config.protocol_id,
            protocol_name=self.config.protocol_name,
            chain_id=chain_id,
            alert_type=alert_type,
            severity=severity,
            timestamp=datetime.now(timezone.utc),
            tx_hash=tx_hash,
            block_number=block_number,
            title=title,
            description=description,
            value_usd=value_usd,
            affected_address=affected_address,
            affected_pool=affected_pool,
            metadata=metadata or {}
        )
        
        logger.warning(
            "protocol_alert_generated",
            protocol=self.config.protocol_id,
            alert_type=alert_type.value,
            severity=severity,
            chain=chain_id,
            value_usd=value_usd
        )
        
        await self._notify_handlers(alert)
        
        return alert
