apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel3

resources:
  - namespace.yaml
  - deployment.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: sentinel3
  app.kubernetes.io/component: core
  app.kubernetes.io/part-of: sentinel3
  app.kubernetes.io/managed-by: kustomize

